# Site settings
title: Trinhgineer
email: scott@scotttrinh.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Scott Trinh, a web developer from Atlanta, Georgia,
  United States. Mostly about technology, with a light smattering of
  philosophy, economics and local affairs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scotttrinh.github.io" # the base hostname & protocol for your site
twitter_username: scotttrinh
github_username:  scotttrinh

# Build settings
markdown: kramdown
